version: "3.7"
services:
  db:
    image: postgres
    container_name: db
    restart: "always"
    env_file:
      - env/db.env
    volumes:
      - "~/deployable_db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  backend:
    depends_on:
      - db
    container_name: backend
    restart: "always"
    build:
      context: ./backend
    env_file:
      - env/backend.env
    environment:
      PORT: 4000
    ports:
      - "4000:4000"

  frontend:
    container_name: frontend
    restart: "always"
    build:
      context: ./frontend
    environment:
      PORT: 3000
    ports:
      - "3000:3000"

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
