version: "3.7"
services:
  db:
    image: postgres
    container_name: db
    restart: "always"
    env_file:
      - db.env
    volumes:
      - "~/pgdata:/var/lib/postgresql/volume"
    ports:
      - "5432:5432"

  backend:
    image: deployable-backend
    depends_on:
      - db
    container_name: backend
    restart: "always"
    env_file:
      - backend.env
    ports:
      - "80:8080"
